# Use official Python runtime as a base image
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY ev_charging_producer.py ./

# Set environment variables (placeholders)
ENV EVENT_HUB_NAMESPACE="XXX.servicebus.windows.net:9093"
ENV EVENT_HUB_NAME="XXX"
ENV CONNECTION_STRING="XXX"

# Command to run the application
CMD ["python", "ev_charging_producer.py"]
